# Generated by Django 3.0.4 on 2020-03-24 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0001_initial'),
        ('Ordenes_ST', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('R', 'Reparado'), ('E', 'Espera Repuesto'), ('P', 'Pendiente Reparación'), ('D', 'Devolución')], max_length=4, verbose_name='Estado. '),
        ),
        migrations.AlterField(
            model_name='ordenesst',
            name='tipo_equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipos.TipoEquipo', verbose_name='Tipo De Equipo.'),
        ),
    ]
