# Generated by Django 3.0.4 on 2020-03-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_ST', '0004_auto_20200329_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('D', 'Devolución'), ('R', 'Reparado'), ('P', 'Pendiente Reparación'), ('E', 'Espera Repuesto')], max_length=4, verbose_name='Estado. '),
        ),
    ]
