# Generated by Django 3.0.4 on 2020-03-31 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0010_auto_20200331_2150'),
        ('Ordenes_ST', '0007_auto_20200331_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('E', 'Espera Repuesto'), ('P', 'Pendiente Reparación'), ('R', 'Reparado'), ('D', 'Devolución')], max_length=4, verbose_name='Estado. '),
        ),
        migrations.CreateModel(
            name='AnularSt',
            fields=[
                ('id_anular_st', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('observacion', models.TextField(verbose_name='Observaciones.')),
                ('id_colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Colaborador.Colaboradores')),
                ('id_orden_st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ordenes_ST.OrdenesSt')),
            ],
        ),
    ]
