# Generated by Django 3.0.4 on 2020-03-31 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_ST', '0008_auto_20200331_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('R', 'Reparado'), ('P', 'Pendiente Reparación'), ('E', 'Espera Repuesto'), ('D', 'Devolución')], max_length=4, verbose_name='Estado. '),
        ),
    ]
