# Generated by Django 3.0.4 on 2020-03-31 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_ST', '0009_auto_20200331_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('D', 'Devolución'), ('E', 'Espera Repuesto'), ('P', 'Pendiente Reparación'), ('R', 'Reparado')], max_length=4, verbose_name='Estado. '),
        ),
    ]
