# Generated by Django 3.0.4 on 2020-03-31 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_ST', '0010_auto_20200331_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente Reparación'), ('E', 'Espera Repuesto'), ('D', 'Devolución'), ('R', 'Reparado')], max_length=4, verbose_name='Estado. '),
        ),
    ]
