# Generated by Django 3.0.4 on 2020-03-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_ST', '0011_auto_20200331_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('D', 'Devolución'), ('R', 'Reparado'), ('P', 'Pendiente Reparación'), ('E', 'Espera Repuesto')], max_length=4, verbose_name='Estado. '),
        ),
    ]
