# Generated by Django 3.0.4 on 2020-04-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_ST', '0013_auto_20200401_0103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenesst',
            old_name='cliente_documento',
            new_name='identificacion_cliente',
        ),
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('E', 'Espera Repuesto'), ('D', 'Devolución'), ('P', 'Pendiente Reparación'), ('R', 'Reparado')], max_length=4, verbose_name='Estado. '),
        ),
    ]
