# Generated by Django 3.0.4 on 2020-04-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_ST', '0014_auto_20200401_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anularst',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('R', 'Reparado'), ('P', 'Pendiente Reparación'), ('E', 'Espera Repuesto'), ('D', 'Devolución')], max_length=4, verbose_name='Estado. '),
        ),
    ]
