# Generated by Django 3.0.4 on 2020-04-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_ST', '0020_auto_20200401_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('D', 'Devolución'), ('R', 'Reparado'), ('E', 'Espera Repuesto'), ('P', 'Pendiente Reparación')], max_length=4, verbose_name='Estado. '),
        ),
    ]
