# Generated by Django 3.0.4 on 2020-04-01 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0024_auto_20200401_0155'),
        ('Ordenes_ST', '0021_auto_20200401_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('R', 'Reparado'), ('P', 'Pendiente Reparación'), ('E', 'Espera Repuesto'), ('D', 'Devolución')], max_length=4, verbose_name='Estado. '),
        ),
        migrations.CreateModel(
            name='OrdenReparadaSt',
            fields=[
                ('id_orden_reparada_st', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Valor del servicio.')),
                ('solucion', models.TextField(verbose_name='Solucion.')),
                ('id_colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Colaborador.Colaboradores', verbose_name='Nombre de quien entrega.')),
                ('id_orden_st', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Ordenes_ST.OrdenesSt')),
            ],
        ),
    ]
