# Generated by Django 3.0.4 on 2020-04-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ordenes_ST', '0022_auto_20200401_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenesst',
            name='estado',
            field=models.CharField(choices=[('D', 'Devolución'), ('P', 'Pendiente Reparación'), ('E', 'Espera Repuesto'), ('R', 'Reparado')], max_length=4, verbose_name='Estado. '),
        ),
    ]
