# Generated by Django 3.0.4 on 2020-03-23 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sucursal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('identificacion_cliente', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Identificaón Cliente')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre Cliente')),
                ('celular', models.CharField(max_length=10, verbose_name='Numero De Celular')),
                ('email', models.EmailField(max_length=254)),
                ('direeccion', models.CharField(max_length=20, verbose_name='Dirección')),
                ('fecha_nacimientos', models.DateField()),
                ('id_empresa', models.CharField(max_length=20)),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sucursal.Sucursal')),
            ],
        ),
    ]
