# Generated by Django 3.0.4 on 2020-03-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('id_colaborador', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion_colaborador', models.CharField(max_length=20, verbose_name='Identificación')),
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre. ')),
                ('celular', models.CharField(max_length=10, verbose_name='Número Celular. ')),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=255, verbose_name='Direccion.')),
                ('foto', models.ImageField(upload_to='')),
                ('rh', models.CharField(choices=[('RH', 'AB-'), ('RH', 'O+'), ('RH', 'A-'), ('RH', 'AB+'), ('RH', 'O-'), ('RH', 'B+'), ('RH', 'A+'), ('RH', 'B-')], default='AB+', max_length=8)),
                ('hoja_de_vida', models.FileField(upload_to='')),
                ('fecha_inicio_trabajo', models.DateField()),
                ('contrato', models.CharField(max_length=2)),
                ('id_cargo', models.CharField(max_length=2)),
                ('porcentaje_utilidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pago_porcentaje', models.DecimalField(decimal_places=2, max_digits=6)),
                ('maximo_valor_prestamo', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
