# Generated by Django 3.0.4 on 2020-03-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaboradores',
            name='id_colaborador',
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='identificacion_colaborador',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='maximo_valor_prestamo',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Maximo Valor Prestado'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='pago_porcentaje',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Pago Porcentaje'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='porcentaje_utilidad',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Porcentaje Utilidad '),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='rh',
            field=models.CharField(choices=[('RH', 'O-'), ('RH', 'B-'), ('RH', 'O+'), ('RH', 'A+'), ('RH', 'AB+'), ('RH', 'A-'), ('RH', 'B+'), ('RH', 'AB-')], max_length=8),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Salario'),
        ),
    ]
