# Generated by Django 3.0.4 on 2020-03-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0003_auto_20200323_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='rh',
            field=models.CharField(choices=[('RH', 'B+'), ('RH', 'B-'), ('RH', 'O+'), ('RH', 'A+'), ('RH', 'AB-'), ('RH', 'O-'), ('RH', 'AB+'), ('RH', 'A-')], max_length=8),
        ),
    ]
