# Generated by Django 3.0.4 on 2020-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0004_auto_20200323_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='rh',
            field=models.CharField(choices=[('RH', 'B+'), ('RH', 'A-'), ('RH', 'A+'), ('RH', 'O+'), ('RH', 'O-'), ('RH', 'B-'), ('RH', 'AB-'), ('RH', 'AB+')], max_length=8),
        ),
    ]
