# Generated by Django 3.0.4 on 2020-03-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0005_auto_20200329_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='rh',
            field=models.CharField(choices=[('RH', 'AB+'), ('RH', 'O+'), ('RH', 'O-'), ('RH', 'B+'), ('RH', 'B-'), ('RH', 'A-'), ('RH', 'AB-'), ('RH', 'A+')], max_length=8),
        ),
    ]
