# Generated by Django 3.0.4 on 2020-03-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0013_auto_20200331_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='rh',
            field=models.CharField(choices=[('RH', 'AB-'), ('RH', 'B-'), ('RH', 'O-'), ('RH', 'A-'), ('RH', 'B+'), ('RH', 'A+'), ('RH', 'AB+'), ('RH', 'O+')], max_length=8),
        ),
    ]
