# Generated by Django 3.0.4 on 2020-04-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Colaborador', '0022_auto_20200401_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='rh',
            field=models.CharField(choices=[('RH', 'O+'), ('RH', 'A-'), ('RH', 'AB+'), ('RH', 'B-'), ('RH', 'A+'), ('RH', 'AB-'), ('RH', 'O-'), ('RH', 'B+')], max_length=8),
        ),
    ]
