# Generated by Django 3.0.4 on 2020-03-24 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Marca.')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id_tipo_equipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Equipo.')),
                ('descripcion', models.TextField(verbose_name='Descripción.')),
            ],
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=200, verbose_name='Modelo.')),
                ('id_marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipos.Marcas')),
            ],
        ),
        migrations.AddField(
            model_name='marcas',
            name='id_tipo_equipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Equipos.TipoEquipo'),
        ),
    ]
