# Generated by Django 3.0.4 on 2020-03-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Id Empresa.')),
                ('nombre_sucursal', models.CharField(max_length=255, verbose_name='Nombre Socursal.')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Direccion.')),
                ('coordenadas', models.CharField(blank=True, max_length=255, verbose_name='Coordenadas')),
                ('telefono', models.CharField(max_length=255, verbose_name='Telefono Contacto')),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('regimen', models.CharField(max_length=100)),
                ('texto_ley_st', models.CharField(max_length=255)),
                ('texto_ley_ventas', models.CharField(max_length=255)),
            ],
        ),
    ]
