# Generated by Django 3.0.4 on 2020-03-23 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
        ('Sucursal', '0003_auto_20200323_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='id_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empresa.Empresas'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='regimen',
            field=models.CharField(choices=[('S', 'Simplificado'), ('C', 'Común')], default='C', max_length=2),
        ),
    ]
