# Generated by Django 3.0.4 on 2020-03-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
        ('Sucursal', '0004_auto_20200323_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='id_empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Empresa.Empresas'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='regimen',
            field=models.CharField(choices=[('C', 'Común'), ('S', 'Simplificado')], default='C', max_length=2),
        ),
    ]
