# Generated by Django 3.0.4 on 2020-03-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sucursal', '0008_auto_20200323_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='regimen',
            field=models.CharField(choices=[('C', 'Común'), ('S', 'Simplificado')], default='C', max_length=2),
        ),
    ]
