# Generated by Django 3.0.4 on 2020-03-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False, verbose_name='Idetendificación Empresa.')),
                ('nombre_empresa', models.CharField(max_length=50, verbose_name='Nombre Empresa.')),
                ('telefono', models.CharField(max_length=50, verbose_name='Número Telefono.')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección.')),
                ('pagina_web', models.URLField(verbose_name='Pagina Web. ')),
            ],
        ),
    ]
